[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = '0.8.26'
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1000

[profile.dev]
optimizer = false 
optimizer_runs = 0  
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
